#!/usr/bin/python

import random
import cgitb
import cgi
cgitb.enable(1)
form = cgi.FieldStorage()
_1rock = form.getvalue('1radioRock')
_2paper = form.getvalue('2radioPaper')
_3scissors = form.getvalue('3radioScissors')
_4rock = form.getvalue('4radioRock')
_5paper = form.getvalue('5radioPaper')
_6scissors = form.getvalue('6radioScissors')

print("<h1>{}, {}, {}, {}, {}, {}</h1>", _1rock, _2paper, _3scissors, _4rock, _5paper, _6scissors )

print("<h1>" +
            "--------------------------------------------------------</br>" +
            "_.-*'*-.__.-*'*-._ Roshambo _.-*'*-.__.-*'*-._</br>" +
            "--------------------------------------------------------</br>" +
        "</h1>")

def play():
    print("----------------------------------------------")
    print("What's your play?")
    player_choices = [0, 0]
    i = 0
    while i < 2:
        print("Hand #{}".format(i + 1))
        player_choices[i] = int(input("Rock (1), Paper (2), or Scissors (3)?\n"))
        i += 1
    opponent_choices = [random.randint(1, 3), random.randint(1, 3)]

    i = 0
    for choice in player_choices:
        if player_choices[i] == opponent_choices[i]:
            print("You both chose the same thing for Hand #{}.".format(i + 1))
            print("It's a draw!\n")
        else:
            if player_choices[i] == 1:
                if opponent_choices[i] == 3:
                    print("Opponent chose Scissors.")
                    print("Hand #{} Won!\n".format(i + 1))
                else:
                    print("Opponent chose Paper.")
                    print("Sorry, Hand #{} Lost!\n".format(i + 1))
            elif player_choices[i] == 2:
                if opponent_choices[i] == 1:
                    print("Opponent chose Rock.")
                    print("Hand #{} Won!\n".format(i + 1))
                else:
                    print("Opponent chose Scissors")
                    print("Sorry, Hand #{} Lost!\n".format(i + 1))
            elif player_choices[i] == 3:
                if opponent_choices[i] == 2:
                    print("Opponent chose Paper")
                    print("Hand #{} Won!\n".format(i + 1))
                else:
                    print("Opponent chose Rock.")
                    print("Sorry, Hand #{} Lost!\n".format(i + 1))
        i += 1

# Get user input.
#while True:
#    play()






